package org.zalando.problem;

/*
 * ⁣​
 * Problem
 * ⁣⁣
 * Copyright (C) 2015 Zalando SE
 * ⁣⁣
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ​⁣
 */

import javax.annotation.concurrent.Immutable;
import javax.ws.rs.core.Response.StatusType;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

import static java.util.stream.Collectors.joining;

/**
 * @see <a href="https://tools.ietf.org/html/draft-nottingham-http-problem-07">Problem Details for HTTP APIs</a>
 */
@Immutable
// TODO document that type, title and status are *NOT* optional, in contrast to the spec
public interface Problem {

    /**
     * An absolute URI that identifies the problem type. When dereferenced,
     * it SHOULD provide human-readable documentation for the problem type
     * (e.g., using HTML). When this member is not present, its value is
     * assumed to be "about:blank".
     *
     * @return an absolute URI that identifies this problem's type
     */
    URI getType();

    /**
     * A short, human-readable summary of the problem type. It SHOULD NOT
     * change from occurrence to occurrence of the problem, except for
     * purposes of localisation.
     *
     * @return a short, human-readable summary of this problem
     */
    String getTitle();

    /**
     * The HTTP status code generated by the origin server for this
     * occurrence of the problem.
     *
     * @return the HTTP status code
     */
    StatusType getStatus();

    /**
     * A human readable explanation specific to this occurrence of the problem.
     *
     * @return A human readable explaination of this problem
     */
    default Optional<String> getDetail() {
        return Optional.empty();
    }

    /**
     * An absolute URI that identifies the specific occurrence of the problem.
     * It may or may not yield further information if dereferenced.
     *
     * @return an absolute URI that identifies this specific problem
     */
    default Optional<URI> getInstance() {
        return Optional.empty();
    }

    /**
     * Optional, additional attributes of the problem. Implementations can choose to ignore this in favor of concrete,
     * typed fields.
     *
     * @return additional parameters
     */
    default Map<String, Object> getParameters() {
        return Collections.emptyMap();
    }

    static ProblemBuilder builder() {
        return new ProblemBuilder();
    }

    static ThrowableProblem valueOf(final StatusType status) {
        return GenericProblems.create(status).build();
    }

    static ThrowableProblem valueOf(final StatusType status, final String detail) {
        return GenericProblems.create(status).withDetail(detail).build();
    }

    static ThrowableProblem valueOf(final StatusType status, final URI instance) {
        return GenericProblems.create(status).withInstance(instance).build();
    }

    static ThrowableProblem valueOf(final StatusType status, final String detail, final URI instance) {
        return GenericProblems.create(status).withDetail(detail).withInstance(instance).build();
    }

    /**
     * Specification by example:
     * <p>
     * <pre>{@code
     *   // Returns "about:blank{404, Not Found}"
     *   Problem.valueOf(NOT_FOUND).toString();
     *
     *   // Returns "about:blank{404, Not Found, Order 123}"
     *   Problem.valueOf(NOT_FOUND, "Order 123").toString();
     *
     *   // Returns "about:blank{404, Not Found, instance=https://example.org/}"
     *   Problem.valueOf(NOT_FOUND, URI.create("https://example.org/")).toString();
     *
     *   // Returns "about:blank{404, Not Found, Order 123, instance=https://example.org/"}
     *   Problem.valueOf(NOT_FOUND, "Order 123", URI.create("https://example.org/")).toString();
     *
     *   // Returns "https://example.org/problem{422, Oh, oh!, Crap., instance=https://example.org/problem/123}
     *   Problem.builder()
     *       .withType(URI.create("https://example.org/problem"))
     *       .withTitle("Oh, oh!")
     *       .withStatus(UNPROCESSABLE_ENTITY)
     *       .withDetail("Crap.")
     *       .withInstance(URI.create("https://example.org/problem/123"))
     *       .build()
     *       .toString();
     * }</pre>
     *
     * @param problem the problem
     * @return a string representation of the problem
     * @see Problem#valueOf(StatusType)
     * @see Problem#valueOf(StatusType, String)
     * @see Problem#valueOf(StatusType, URI)
     * @see Problem#valueOf(StatusType, String, URI)
     */
    static String toString(final Problem problem) {
        final ArrayList<String> parts = new ArrayList<>(Arrays.asList(
            Integer.toString(problem.getStatus().getStatusCode()),
            problem.getTitle(),
            problem.getDetail().orElse(null),
            problem.getInstance().map(i -> "instance=" + i).orElse(null)
        ));

        problem.getParameters().forEach((k, v) -> Optional.ofNullable(v).ifPresent(t -> parts.add(k + "=" + t)));

        return problem.getType().toString()
            + "{"
            + parts.stream().filter(Objects::nonNull).collect(joining(", "))
            + "}";
    }

}
